const SUPABASE_URL = 'https://neknhffhhmisarcstinj.supabase.co';
const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5la25oZmZoaG1pc2FyY3N0aW5qIiwicm9sZSI6ImFub24iLCJpYXQiOjE2NTY1Mzg4MDMsImV4cCI6MTk3MjExNDgwM30.W45kODzm7MA_wLAcJ-ZLL3F00C1elWqKfbg4Slby9Og';

export const client = supabase.createClient(SUPABASE_URL, SUPABASE_KEY);